name: E2E tests
on:
  pull_request:
    branches: [ main ]

jobs:
  integration-tests:
    strategy:
      matrix:
        python_version: ['3.10']
        node_version: ['18']
        os: [macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out source code
        uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Use cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ matrix.node_version }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install test app dependencies
        run: npm run build:test-app
      - name: Setup Python Env
        run: |
          python -m pip install --upgrade pip
          python --version
          python -m pip install -e .
      - name: Run e2e tests
        run: python example/spectron_with_test_app.py